import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import UseRedux from './components/hooks/UseRedux';

const geistSans = localFont({
  src: './fonts/sourceCodeMono3.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
});
const geistMono = localFont({
  src: './fonts/sourceCode3.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
});

export const metadata: Metadata = {
  title: 'Noted Whatsab',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <UseRedux>{children}</UseRedux>
      </body>
    </html>
  );
}
